### ISSUE TITLE
360 Deg video from mobile

### ISSUE THREAD

**Issue by Miniz199922** [commaai/connect#347] opened 2023-03-08 13:54 UTC
Hello, I cannot view the 360 deg clip from android mobile. Only pc.

**Comment by incognitojam** [comment] 2023-07-10 14:15
Duplicate of https://github.com/commaai/connect/issues/282. Are you still facing this problem? It seems to be resolved on my android phone.

**Closed as not planned** 2023-07-10 14:15 UTC
